CREATE TABLE mathtype(
    course_name TEXT not null,
    mathlvl TEXT not null);

INSERT INTO mathtype(course_name,mathlvl) 
     VALUES ('MATH92','REMEDIAL'),
     ('MATH92OL','REMEDIAL'),
     ('MATH93','REMEDIAL'),
     ('MATH93OL','REMEDIAL'),
     ('MATH96A','REMEDIAL'),
     ('MATH96S','REMEDIAL'),
     ('MATH97','REMEDIAL'),
     ('MATH99','REMEDIAL'),
     ('ESM91A','REMEDIAL'),
     ('ESM91B','REMEDIAL'),
     ('ESM92','REMEDIAL'),
     ('ESM96LI','REMEDIAL'),
     ('ESM96LII','REMEDIAL'),
     ('ESM96S','REMEDIAL'),
     ('ESM97','REMEDIAL'),
     ('ESM99','REMEDIAL'),
     ('MATH102','NOTREMEDIAL'),
     ('MATH103','NOTREMEDIAL'),
     ('MATH103L','NOTREMEDIAL'),
     ('MATH104','NOTREMEDIAL'),
     ('MATH105','NOTREMEDIAL'),
     ('MATH131','NOTREMEDIAL'),
     ('MATH131HON','NOTREMEDIAL'),
     ('MATH131OL','NOTREMEDIAL'),
     ('MATH140','NOTREMEDIAL'),
     ('MATH140HON','NOTREMEDIAL'),
     ('MATH140OL','NOTREMEDIAL'),
     ('MATH150A','CALC+'),
     ('MATH150AL','CALC+'),
     ('MATH150B','CALC+'),
     ('MATH150BL','CALC+'),
     ('MATH196LOL','NOT_IN_CATALOG'),
     ('MATH210','NOTREMEDIAL'),
     ('MATH250','CALC+'),
     ('MATH255A','CALC+'),
     ('MATH255B','CALC+'),
     ('MATH262','CALC+'),
     ('MATH280','CALC+'),
     ('MATH310','NOTREMEDIAL'),
     ('MATH331','NOTREMEDIAL'),
     ('MATH331OL','NOTREMEDIAL'),
     ('MATH340','CALC+'),
     ('NONE','NONE'),
     ('ENGL495ESM','NOTMATH');
